FROM python:3.11-slim

WORKDIR /opt/stock

COPY stock/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY stock/ .

EXPOSE 8000
CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
